### ISSUE TITLE
why fails with AttributeError: 'Traceback' object has no attribute 'positions'

### ISSUE THREAD

**Issue by jooray** [plasma-umass/ChatDBG#1]
I get this error

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.10_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/homebrew/Cellar/python@3.10/3.10.10_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/juraj/tmp/models/lib/python3.10/site-packages/chatdbg/__main__.py", line 22, in <module>
    main()
  File "/Users/juraj/tmp/models/lib/python3.10/site-packages/chatdbg/__main__.py", line 20, in main
    chatdbg.main()
  File "/Users/juraj/tmp/models/lib/python3.10/site-packages/chatdbg/chatdbg.py", line 1789, in main
    pdb.interaction(None, t)
  File "/Users/juraj/tmp/models/lib/python3.10/site-packages/chatdbg/chatdbg.py", line 428, in interaction
    self._cmdloop()
  File "/Users/juraj/tmp/models/lib/python3.10/site-packages/chatdbg/chatdbg.py", line 393, in _cmdloop
    self.cmdloop()
  File "/opt/homebrew/Cellar/python@3.10/3.10.10_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/Users/juraj/tmp/models/lib/python3.10/site-packages/chatdbg/chatdbg.py", line 493, in onecmd
    return cmd.Cmd.onecmd(self, line)
  File "/opt/homebrew/Cellar/python@3.10/3.10.10_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/cmd.py", line 217, in onecmd
    return func(arg)
  File "/Users/juraj/tmp/models/lib/python3.10/site-packages/chatdbg/chatdbg.py", line 996, in do_why
    asyncio.run(chatdbg_why.why(self, arg))
  File "/opt/homebrew/Cellar/python@3.10/3.10.10_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/homebrew/Cellar/python@3.10/3.10.10_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/juraj/tmp/models/lib/python3.10/site-packages/chatdbg/chatdbg_why.py", line 51, in why
    positions = inspect.getframeinfo(frame).positions
AttributeError: 'Traceback' object has no attribute 'positions'
```

Regardless of actual exception. I have OPENAPI_AI_KEY set up.

There is no "why" for this exception 😅

**Comment by emeryberger** [comment]
Thanks for the report! Did you run this with `chatdbg -c continue yourprogram.py` (or the equivalent with `python3 -m`)? Did you install it from `pip`? What version? (Do `pip list | grep ChatDBG`) If you can walk through the steps that got you to this point, that'd be helpful (and of course, your code if possible!).

**Comment by emeryberger** [comment]
If you use `pip`, please go ahead and `python3 -m pip install -U chatdbg` to make sure you have the latest version.

**Comment by jooray** [comment]
I did the upgrade through pip.

This is the output of pip list | grep ChatDBG
```
ChatDBG                      0.0.3
```

I ran:

```
python3 -m chatdbg -c continue test.py
```

**Comment by emeryberger** [comment]
Can you share `test.py`? And is the output the same? (I ask because the line number in the final report doesn't correspond to where that code is now.)

**Comment by jooray** [comment]
I did a minimal test case.

test1.py:

```python
print (17/0)
```

Complete output:

```
python3 -m chatdbg -c continue test1.py
Traceback (most recent call last):
  File "/Users/juraj/tmp/models/lib/python3.10/site-packages/chatdbg/chatdbg.py", line 1770, in main
    pdb._run(target)
  File "/Users/juraj/tmp/models/lib/python3.10/site-packages/chatdbg/chatdbg.py", line 1648, in _run
    self.run(target.code)
  File "/opt/homebrew/Cellar/python@3.10/3.10.10_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/bdb.py", line 597, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/Users/juraj/tmp/models/alpacoom/test1.py", line 1, in <module>
    print (17/0)
ZeroDivisionError: division by zero
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> /Users/juraj/tmp/models/alpacoom/test1.py(1)<module>()
-> print (17/0)
(Pdb) why
Traceback (most recent call last):
  File "/Users/juraj/tmp/models/lib/python3.10/site-packages/chatdbg/chatdbg.py", line 1770, in main
    pdb._run(target)
  File "/Users/juraj/tmp/models/lib/python3.10/site-packages/chatdbg/chatdbg.py", line 1648, in _run
    self.run(target.code)
  File "/opt/homebrew/Cellar/python@3.10/3.10.10_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/bdb.py", line 597, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/Users/juraj/tmp/models/alpacoom/test1.py", line 1, in <module>
    print (17/0)
ZeroDivisionError: division by zero

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.10_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/homebrew/Cellar/python@3.10/3.10.10_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/juraj/tmp/models/lib/python3.10/site-packages/chatdbg/__main__.py", line 22, in <module>
    main()
  File "/Users/juraj/tmp/models/lib/python3.10/site-packages/chatdbg/__main__.py", line 20, in main
    chatdbg.main()
  File "/Users/juraj/tmp/models/lib/python3.10/site-packages/chatdbg/chatdbg.py", line 1789, in main
    pdb.interaction(None, t)
  File "/Users/juraj/tmp/models/lib/python3.10/site-packages/chatdbg/chatdbg.py", line 428, in interaction
    self._cmdloop()
  File "/Users/juraj/tmp/models/lib/python3.10/site-packages/chatdbg/chatdbg.py", line 393, in _cmdloop
    self.cmdloop()
  File "/opt/homebrew/Cellar/python@3.10/3.10.10_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/Users/juraj/tmp/models/lib/python3.10/site-packages/chatdbg/chatdbg.py", line 493, in onecmd
    return cmd.Cmd.onecmd(self, line)
  File "/opt/homebrew/Cellar/python@3.10/3.10.10_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/cmd.py", line 217, in onecmd
    return func(arg)
  File "/Users/juraj/tmp/models/lib/python3.10/site-packages/chatdbg/chatdbg.py", line 996, in do_why
    asyncio.run(chatdbg_why.why(self, arg))
  File "/opt/homebrew/Cellar/python@3.10/3.10.10_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/homebrew/Cellar/python@3.10/3.10.10_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/juraj/tmp/models/lib/python3.10/site-packages/chatdbg/chatdbg_why.py", line 51, in why
    positions = inspect.getframeinfo(frame).positions
AttributeError: 'Traceback' object has no attribute 'positions'
```

**Comment by emeryberger** [comment]
OK, not sure what's going on but I pushed the latest version to pypi as version 0.0.4. Please try to upgrade again. I got these results:

```
% chatdbg -c continue test-issue1.py 
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/chatdbg/chatdbg.py", line 1778, in main
    pdb._run(target)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/chatdbg/chatdbg.py", line 1648, in _run
    self.run(target.code)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/bdb.py", line 597, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/Users/emery/tmp/test-issue1.py", line 1, in <module>
    print (17/0)
           ~~^~
ZeroDivisionError: division by zero
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> /Users/emery/tmp/test-issue1.py(1)<module>()
-> print (17/0)
(Pdb) why


The root cause of this error is an attempt to divide a number by zero,
which is not allowed in mathematics. Therefore, the ZeroDivisionError
exception is raised.

To fix this error, the code should be modified to ensure that the
denominator is not zero before performing the division operation. For
example, a conditional statement can be added to check if the
denominator is zero, and if it is, print an error message or return
None. Here is an example fix:

    ```
    denominator = 0
    if denominator == 0:
        print("Error: Denominator cannot be zero.")
    else:
        result = 17 / denominator
        print(result)
    ```

In this modified code, a variable `denominator` is assigned a value of
zero. Then, a conditional statement is added to check if the
denominator is zero. If it is, an error message is printed. If it is
not, the division operation is performed and the result is printed.
```

**Comment by jooray** [comment]
Same:

```
Installing collected packages: chatdbg
  Attempting uninstall: chatdbg
    Found existing installation: ChatDBG 0.0.3
    Uninstalling ChatDBG-0.0.3:
      Successfully uninstalled ChatDBG-0.0.3
Successfully installed chatdbg-0.0.4
(models) juraj@theanine : ~/tmp/models/alpacoom$ python3 -m chatdbg -c continue test1.py
Traceback (most recent call last):
  File "/Users/juraj/tmp/models/lib/python3.10/site-packages/chatdbg/chatdbg.py", line 1778, in main
    pdb._run(target)
  File "/Users/juraj/tmp/models/lib/python3.10/site-packages/chatdbg/chatdbg.py", line 1648, in _run
    self.run(target.code)
  File "/opt/homebrew/Cellar/python@3.10/3.10.10_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/bdb.py", line 597, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/Users/juraj/tmp/models/alpacoom/test1.py", line 1, in <module>
    print (17/0)
ZeroDivisionError: division by zero
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> /Users/juraj/tmp/models/alpacoom/test1.py(1)<module>()
-> print (17/0)
(Pdb) why
Traceback (most recent call last):
  File "/Users/juraj/tmp/models/lib/python3.10/site-packages/chatdbg/chatdbg.py", line 1778, in main
    pdb._run(target)
  File "/Users/juraj/tmp/models/lib/python3.10/site-packages/chatdbg/chatdbg.py", line 1648, in _run
    self.run(target.code)
  File "/opt/homebrew/Cellar/python@3.10/3.10.10_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/bdb.py", line 597, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/Users/juraj/tmp/models/alpacoom/test1.py", line 1, in <module>
    print (17/0)
ZeroDivisionError: division by zero

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.10_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/homebrew/Cellar/python@3.10/3.10.10_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/juraj/tmp/models/lib/python3.10/site-packages/chatdbg/__main__.py", line 22, in <module>
    main()
  File "/Users/juraj/tmp/models/lib/python3.10/site-packages/chatdbg/__main__.py", line 20, in main
    chatdbg.main()
  File "/Users/juraj/tmp/models/lib/python3.10/site-packages/chatdbg/chatdbg.py", line 1797, in main
    pdb.interaction(None, t)
  File "/Users/juraj/tmp/models/lib/python3.10/site-packages/chatdbg/chatdbg.py", line 428, in interaction
    self._cmdloop()
  File "/Users/juraj/tmp/models/lib/python3.10/site-packages/chatdbg/chatdbg.py", line 393, in _cmdloop
    self.cmdloop()
  File "/opt/homebrew/Cellar/python@3.10/3.10.10_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/Users/juraj/tmp/models/lib/python3.10/site-packages/chatdbg/chatdbg.py", line 493, in onecmd
    return cmd.Cmd.onecmd(self, line)
  File "/opt/homebrew/Cellar/python@3.10/3.10.10_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/cmd.py", line 217, in onecmd
    return func(arg)
  File "/Users/juraj/tmp/models/lib/python3.10/site-packages/chatdbg/chatdbg.py", line 996, in do_why
    asyncio.run(chatdbg_why.why(self, arg))
  File "/opt/homebrew/Cellar/python@3.10/3.10.10_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/homebrew/Cellar/python@3.10/3.10.10_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/juraj/tmp/models/lib/python3.10/site-packages/chatdbg/chatdbg_why.py", line 72, in why
    positions = inspect.getframeinfo(frame).positions
AttributeError: 'Traceback' object has no attribute 'positions'
```

**Comment by emeryberger** [comment]
Thanks for the additional report! I figured it out: it was a Python version issue (I am using 3.11). I just tested this with Python 3.10 and it worked. Please upgrade again and let me know.

**Comment by jooray** [comment]
Perfect, I confirm it works. I use both Python 3.10 and 3.11, but this was 3.10 indeed, pytorch does not work with 3.11, so all AI stuff I do with 3.10.

Current version (0.0.8) works.
