### ISSUE TITLE
AttributeError: module 'lldb' has no attribute 'SBDebugger'

### ISSUE THREAD

**Issue by ramseyxu** [plasma-umass/ChatDBG#7]
Could you help me with this issue?

env:
Linux fc10339df926 5.4.126-1.el7.elrepo.x86_64 #1 SMP Mon Jun 14 17:48:40 EDT 2021 x86_64 x86_64 x86_64 GNU/Linux

debugger: lldb 14.0.0

compiler: clang++15

python and pip:
```
Python 3.10.6
pip 22.0.2 from /usr/lib/python3/dist-packages/pip (python 3.10)
```

install command
```
apt update
apt-get install python3-pip -y
python3 -m pip install chatdbg
python3 -c 'import chatdbg; print(f"command script import {chatdbg.__path__[0]}/chatdbg_lldb.py")' >> ~/.lldbinit
```

~/.lldbinit
```
command script import /usr/local/lib/python3.10/dist-packages/chatdbg/chatdbg_lldb.py
```

usage:
I want to use LLDB to debug my unit test, and meet this error
```
lldb ./src/unit_tests_dbms

root@fc10339df926:/clickhouse/build_debug_# lldb ./src/unit_tests_dbms
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'lldb.embedded_interpreter'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'lldb' is not defined
error: module importing failed: Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/chatdbg/chatdbg_lldb.py", line 8, in <module>
    def __lldb_init_module(debugger: lldb.SBDebugger, internal_dict: dict) -> None:
AttributeError: module 'lldb' has no attribute 'SBDebugger'
```

**Comment by emeryberger** [comment]
I can't reproduce with the current version. Please try `python3 -m pip install -U chatdbg` and try again.

**Comment by ramseyxu** [comment]
I used chatdbg in Docker, here's my dockerfile, hoping can reproduce the bug with it
```
from ubuntu
RUN apt-get update && apt-get install -y git cmake ccache python3 ninja-build wget lldb lsb-release software-properties-common libzstd-dev libhiredis-dev && echo "lldb installed successfully"
RUN bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
RUN apt-get install -y libprotobuf-dev protobuf-compiler
```

**Comment by emeryberger** [comment]
This is a pretty incomplete docker file. Can you produce one that allows me to directly reproduce the issue (or try to)? Alternatively, please try the latest version, which at least fixed an issue on Mac, so perhaps it will help (the newest version of one of the dependencies was broken).

**Comment by emeryberger** [comment]
Closing for lack of response.

**Comment by nicovank** [comment]
Commenting here since I ran into the same issue today, the issue may come from certain LLDB versions.
On my laptop currently, the error reproduces with LLDB 14.0.0, but ChatDBG works with LLDB 17.0.2.
